/*

Sean Cotterill

Live Coding set, based on tuned percussion.

Available on https://github.com/theseanco/co34pt_livecode

For KOAN.

Thanks to Martin.

Archipelago are mint.

Sounds:

brec - field recording

mhit - metal hits
[0] - metal bar hit

mgest - metal  gestures
[0] - Metal bar multihit

bhit - bass hit

bowl - bowl hit

~henon = Pbind(\instrument,\henon,\a,Pexprand(1.3,1.30001),\b,Pexprand(0.3,0.300001),\atk,0,\sus,0,\rel,0.04,\freq,44100,\amp,10,\pan,Pwhite(-1.0,1),\dur,0.125)

*/
